Vagrant.configure(2) do |config|
  config.vm.define "1-single-network-namespace" do |p1|
      p1.vm.box = "ubuntu/jammy64"
      p1.vm.network :private_network, ip: "10.0.0.10", virtualbox__intnet: "network1"
      p1.vm.hostname = "1-single-network-namespace"
  end
  config.vm.box_check_update = false
  config.vbguest.auto_update = false
end
